apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dgraph-grpc-ingress
  namespace: dgraph
  annotations:
    konghq.com/protocols: "grpc, grpcs" 
spec:
  ingressClassName: kong
  rules:
  - host: dgraph-grpc.app.com 
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: dgraph-grpc-service 
            port:
              number: 9080 