apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dgraph-http-ingress   
  namespace: dgraph
  annotations:
    konghq.com/protocols: "http, https"  
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
  - host: dgraph-http.app.com  
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dgraph-http-service
            port:
              number: 8080      