apiVersion: v1
kind: Service
metadata:
  name: wg-service
  namespace: wireguard
spec:
  type: NodePort
  selector:
    app: wireguard
  ports:
  - name: wireguard
    protocol: UDP
    port: 51820
    targetPort: 51820
    nodePort: 30080
